services:
  - type: web
    name: verida-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm install --save-dev @types/cors @types/express @types/jsonwebtoken @types/morgan @types/ws @types/node && npm run build --workspace=@verida/shared && npm run build --workspace=@verida/api
    startCommand: cd apps/api && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHELBY_NETWORK
        value: testnet
    healthCheckPath: /healthz
    autoDeploy: true
